### ISSUE TITLE
Define Dataset for training

### ISSUE THREAD

**Issue by GeroVanMi** [GeroVanMi/algorithmic-quartet-mlops#1]
In order to train a diffusion model we need a dataset. 
The data can either be static or continously added. 

- [x] Select Dataset and give reasons for why we use it
- [x] Upload dataset to GC
- [x] #4

**Comment by Patrickliuu** [comment]
DVC for data versioning make currently no sense, as we are not trying to re-train the model.

**Comment by GeroVanMi** [comment]
@Patrickliuu It seems you have decided on the Pokemon data, is that right?

**Comment by Patrickliuu** [comment]
The dataset is available under:
[huggan/pokemon](https://huggingface.co/datasets/huggan/pokemon)
