### ISSUE TITLE
Function: Model prediction

### ISSUE THREAD

**Issue by TheMadBevah** [GeroVanMi/algorithmic-quartet-mlops#10]
The server should use the newest/best version of the model based on arbitrary metric - assigned through weights and biases. 
The function should use the model to make a prediction.
This prediction (image) is then returned and given to the Streamlit UI

- Depends on #5,#6, #15

**Comment by GeroVanMi** [comment]
This is now "kind of" done. It currently just selects the "latest" trained version. This should be acceptable for the MVP milestone, so I'm moving it to the Complete Product milestone.
