### ISSUE TITLE
Google Cloud Storage usage for image prediction logging

### ISSUE THREAD

**Issue by TheMadBevah** [GeroVanMi/algorithmic-quartet-mlops#16]
- Depends on #4 
- Depends on #7 
- Depends on #5 

How does the pathing work? significantly different from normal machine?

**Comment by GeroVanMi** [comment]
@TheMadBevah Quick note, you will need a separate Google Cloud storage bucket. The bucket from #4 is meant only for training images. I have created a separate bucket ( zhaw_algorithmic_quartet_generated_images ) for generated images for you.

**Comment by GeroVanMi** [comment]
I have added a "TODO" comment in `generate_images.py` where the relevant code needs to be put. @TheMadBevah maybe you can ask @Patrickliuu about this, since he has implemented the Download Code for the training pipeline already.
