### ISSUE TITLE
Create Streamlit Docker configuration

### ISSUE THREAD

**Issue by GeroVanMi** [GeroVanMi/algorithmic-quartet-mlops#2]
Prepare the Developer Environment for the Frontend.

**Comment by TheMadBevah** [comment]
The streamlit UI has to do two things:
- Make a prediction happen
- Get the prediction from the Google cloud storage

**Comment by Patrickliuu** [comment]
Set env variables:

mkdir .config/gcloud
cp gc.json /teamspace/studios/this_studio/.config/gcloud/application_default_credentials.json
gcloud auth application-default login lightning-ci@algorithmic-quartet.iam.gserviceaccount.com
