### ISSUE TITLE
Choose a tool/the tools for monitoring metrics in training and production

### ISSUE THREAD

**Issue by GeroVanMi** [GeroVanMi/algorithmic-quartet-mlops#20]
**[Weights & Biases](https://docs.wandb.ai/):**
> Positive: 

- [ ] Sweeps (with the config files, where we have all dependencies)
- [ ] The experiments can be well structured and very well followed
- [ ] Integration into existing frameworks
- [ ] Good and professional visualizations
- [ ] supports team collaboration
- [ ] Model Saving and Reproducibility are possible
- [ ] Scalability: It supports scaling from local experiments to large-scale deployments smoothly, making it suitable for both research and production environments.
- [ ] System performance could be checked
- [ ] 

> Negative:

- [ ] Costs
- [ ] Dependency and Privacy

> [Comet.ml](https://www.comet.com/docs/v2/)

- [ ] **Comprehensive Experiment Management:** Tracks code, experiments, and results
- [ ] **Integration:** Supports multiple frameworks and languages, facilitating integration into existing projects without major adjustments.
- [ ] **Community and Support:** Provides good documentation and has a supportive community, which can be helpful for troubleshooting and best practices.

> **[PyTorch](https://pytorch.org/)**

>  [HYDRA ](https://hydra.cc/)

**Pros**
- [ ] **Simplification of Configuration:** HYDRA allows you to create hierarchical configurations dynamically by composing and overriding them from the command line. This simplifies managing configurations for complex applications requiring various setups for different environments or tasks.
- [ ] **Flexibility:** It supports a wide range of data sources for configuration files, including YAML, and it can seamlessly merge configurations from multiple sources. This flexibility is particularly useful in research and development environments where rapid testing of configurations is standard.
- [ ] **Plugin System:** HYDRA includes a robust plugin system, allowing seamless functionality extension and integration with other tools and frameworks.
- [ ] **Command Line Integration:** Configurations can be easily adjusted or overridden from the command line, making it convenient to quickly change parameters without altering code or configuration files directly.

**Cons**

- [ ] **Learning Curve:** Although HYDRA is very powerful, it has a learning curve. Users must become familiar with its configuration composition and overriding principles to use it effectively.
- [ ] **Integration Effort:** While integrating HYDRA into existing projects offers many long-term benefits, the initial setup and integration might require significant effort, especially in projects not designed to use external configuration management.
- [ ] **Dependency and Complexity:** Adding HYDRA introduces another dependency into the project, which can increase the complexity and potentially impact the build and deployment processes.
- [ ] **Overhead for Smaller Projects:** For smaller projects or those that do not require frequent configuration changes or extensive experimentation, the overhead of implementing and maintaining a HYDRA-based configuration might not be justified.

- [ ] [**PyTorch**](https://github.com/Lightning-AI/torchmetrics) - framework supports techniques used in continual learning, like experience replay, elastic weight consolidation (EWC), and other regularization methods
- [ ] [**Avdvertorch**](https://github.com/BorealisAI/advertorch) 

> [Alibi Detect](https://github.com/SeldonIO/alibi-detect) 

**Pros**
- [ ] **Versatility:** Alibi Detect provides a wide range of detection algorithms suitable for various data types, including tabular data, text, images, and time series.
- [ ] **Framework Compatibility**: It supports PyTorch backends for drift detection, making it flexible for use in different machine learning stacks.
- [ ] **Online and Offline Detection:** The library supports both online and offline detection methods, which means it can handle streaming and batch data.
- [ ] **Good documentation**
- [ ] **Ease of Integration:** It can be easily integrated into existing data processing pipelines and machine learning workflows.

**Cons**

- [ ] **Complexity:** The wide range of features and algorithms might be overwhelming for beginners or practitioners new to drift, outlier, and adversarial detection.
- [ ] **Scalability:** Depending on the models' complexity and the data's size, scaling the detectors for high-throughput systems might require additional engineering.
- [ ] **Resource Intensive:** Some detection algorithms, especially for high-dimensional data such as images and time series, can be resource-intensive, requiring significant computational power.
- [ ]

**Comment by GeroVanMi** [comment]
@vollOlga Give a quick ping, once this is ready for review!

**Comment by vollOlga** [comment]
@GeroVanMi I think, I am ready :)

**Comment by GeroVanMi** [comment]
@vollOlga Nice, thanks for the info, I have a few points regarding this: 

1. Thanks for the W&B review! It's really nice and the right level of detail. I would like it even more if you would focus on comparisions, so for example "W&B provides easy team collaboration, which is easier to set up compared to Tensorboard." 
3.  What is the use case for Comet.ml? Where would you like to integrate it in our pipeline? 
4. I see you've added Alibi Detect, which I think could be very cool! However, I am unsure how we would detect data drift. Could you elaborate it a bit, how you were planning to use it? 
5. Same for HYDRA: Where would you add it in the pipeline?
