### ISSUE TITLE
Build Training Pipeline

### ISSUE THREAD

**Issue by Patrickliuu** [GeroVanMi/algorithmic-quartet-mlops#24]
- [ ] Dataset class #1
- [ ] Model class 
- [ ] Pytorch Lightning Trainer
- [x] #12

**Comment by GeroVanMi** [comment]
This is somewhat duplicated with #26 now. Maybe we can close this once 26 is done.

**Comment by GeroVanMi** [comment]
The training works so far though the results are still terrible. I am closing this for now.
