### ISSUE TITLE
Create Google Cloud storage for Training

### ISSUE THREAD

**Issue by Patrickliuu** [GeroVanMi/algorithmic-quartet-mlops#4]
- [ ] Upload dataset to a storage according to: https://cloud.google.com/storage/docs/uploading-objects?hl=de

Why we decided to choose GC:

Positive:
 + data availabilty / distributed, collaboration is a breeze
 + variety of storage modes -> for every need / price
 + Credits granted for GC

Negative:
 - dependence of GC

**Comment by GeroVanMi** [comment]
@Patrickliuu I think this is already done, if so you can close this already.
